swagger: "2.0"
info:
  title: Evgeniy Poznyak Portfolio Website API
  description: API description in Markdown.
  version: 1.0.0
  contact:
    name: Evgeniy Poznyak
    url: "https://evgeniy.poznyaks.com"
    email: evgeniy.poznyak@gmail.com
host: data.evgeniy.poznyaks.com
basePath: /api/
tags:
  - name: "skills"
    description: "Everything about my skills"
    externalDocs:
      description: "Find out more"
      url: "https://evgeniy.poznyaks.com"
  - name: "portfolio"
    description: "Everything about my works"
    externalDocs:
      description: "Find out more"
      url: "https://evgeniy.poznyaks.com"
consumes:
  - application/json # format of the responses to the client
produces:
  - application/json
schemes:
  - https
paths:
  /skills:
    get:
      tags:
        - "skills"
      summary: Return all skills data.
      description: Optional extended description in Markdown.
      produces:
          - application/json
      responses:
          200:
            description: OK
  /portfolio:
    get:
      tags:
        - "portfolio"
      summary: Return all portfolio data.
      description: Optional extended description in Markdown.
      produces:
          - application/json
      responses:
          200:
            description: OK
